name: Test Main

on:
  pull_request:
  push:
    branches:
      - githhub-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      run: yarn
    - name: Build
      run: ENABLE_CLDR=1 yarn build

  test-suite-1:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
    - name: Test
      run: yarn test:main:suite-1

  test-suite-2:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
    - name: Test
      run: yarn test:main:suite-2