name: Test Main

on:
  pull_request:
  push:
    branches:
      - githhub-actions
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install Dependencies
      run: yarn

    - name: Build
      run: ENABLE_CLDR=1 yarn build

    - name: Test
      run: yarn test:main
